version: '3'

services:
  api:
    build: .
    volumes:
      - ./:/app
    links:
      - db
    ports:
      - 3000:3000
  db:
    image: mongo:latest
    command: mongod --port 5000
    environment:
      - MONGO_INITDB_DATABASE = courseData
    ports:
      - 5000:5000
  db_seed:
    build: ./db
    links:
      - db